services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: production_django
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ./.envs/.production/django.env
      - ./.envs/.production/postgresql.env
    command: /start

  db:
    build:
      context: .
      dockerfile: ./compose/production/db/Dockerfile
    image: production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/postgresql.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 2s
      retries: 15

  caddy:
    build:
      context: .
      dockerfile: ./compose/production/caddy/Dockerfile
    image: production_caddy
    depends_on:
      - django
    volumes:
      - production_caddy_data:/data
    env_file:
      - ./.envs/.production/caddy.env
    ports:
      - 80:80
      - 443:443

  redis:
    image: redis:8-alpine

  celeryworker:
    <<: *django
    image: production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: production_celerybeat
    command: /start-celerybeat

volumes:
  production_caddy_data: {}
  production_postgres_data: {}
  production_postgres_data_backups: {}
