services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: local_django
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/django.env
      - ./.envs/.local/postgresql.env
    ports:
      - 8000:8000
    command: /start

  db:
    build:
      context: .
      dockerfile: ./compose/production/db/Dockerfile
    image: local_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/postgresql.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 2s
      retries: 15

  redis:
    image: redis:8-alpine

  celeryworker:
    <<: *django
    image: local_celeryworker
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: local_celerybeat
    ports: []
    command: /start-celerybeat

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
