#!/bin/sh

set -o errexit
set -o nounset

cd \{\{cookiecutter.project_slug\}\}

celery {{cookiecutter.project_slug}}.flower \
    --app=taskapp \
    --broker="${CELERY_BROKER_URL}" \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
